package ip

var (
	// http://zh.wikipedia.org/wiki/ISO_3166-1
	countryCodes = map[string]string{
		"安道尔":        "AD",
		"阿联酋":        "AE",
		"阿富汗":        "AF",
		"安提瓜和巴布达":    "AG",
		"安圭拉":        "AI",
		"阿尔巴尼亚":      "AL",
		"亚美尼亚":       "AM",
		"安哥拉":        "AO",
		"南极洲":        "AQ",
		"阿根廷":        "AR",
		"美属萨摩亚":      "AS",
		"奥地利":        "AT",
		"澳大利亚":       "AU",
		"阿鲁巴":        "AW",
		"奥兰群岛":       "AX",
		"阿塞拜疆":       "AZ",
		"波斯尼亚和黑塞哥维那": "BA",
		"巴巴多斯":       "BB",
		"孟加拉":        "BD",
		"比利时":        "BE",
		"布基纳法索":      "BF",
		"保加利亚":       "BG",
		"巴林":         "BH",
		"布隆迪":        "BI",
		"贝宁":         "BJ",
		"圣巴泰勒米岛":     "BL",
		"百慕大":        "BM",
		"文莱":         "BN",
		"玻利维亚":       "BO",
		"荷兰加勒比":      "BQ",
		"巴西":         "BR",
		"巴哈马":        "BS",
		"不丹":         "BT",
		"布韦岛":        "BV",
		"博茨瓦纳":       "BW",
		"白俄罗斯":       "BY",
		"伯利兹":        "BZ",
		"加拿大":        "CA",
		"科科斯(基林)群岛":  "CC",
		"刚果(金)":      "CD",
		"中非":         "CF",
		"刚果(布)":      "CG",
		"瑞士":         "CH",
		"科特迪瓦":       "CI",
		"库克群岛":       "CK",
		"智利":         "CL",
		"喀麦隆":        "CM",
		"中国":         "CN",
		"哥伦比亚":       "CO",
		"哥斯达黎加":      "CR",
		"古巴":         "CU",
		"佛得角":        "CV",
		"库拉索":        "CW",
		"圣诞岛":        "CX",
		"塞浦路斯":       "CY",
		"捷克":         "CZ",
		"德国":         "DE",
		"吉布提":        "DJ",
		"丹麦":         "DK",
		"多米尼克":       "DM",
		"多米尼加":       "DO",
		"阿尔及利亚":      "DZ",
		"厄瓜多尔":       "EC",
		"爱沙尼亚":       "EE",
		"埃及":         "EG",
		"西撒哈拉":       "EH",
		"厄立特里亚":      "ER",
		"西班牙":        "ES",
		"埃塞俄比亚":      "ET",
		"芬兰":         "FI",
		"斐济":         "FJ",
		"福克兰群岛":      "FK",
		"密克罗尼西亚联邦":   "FM",
		"法罗群岛":       "FO",
		"法国":         "FR",
		"加蓬":         "GA",
		"英国":         "GB",
		"格林纳达":       "GD",
		"格鲁吉亚":       "GE",
		"法属圭亚那":      "GF",
		"根西岛":        "GG",
		"加纳":         "GH",
		"直布罗陀":       "GI",
		"格陵兰":        "GL",
		"冈比亚":        "GM",
		"几内亚":        "GN",
		"瓜德罗普":       "GP",
		"赤道几内亚":      "GQ",
		"希腊":         "GR",
		"南乔治亚岛和南桑威奇群岛": "GS",
		"危地马拉":         "GT",
		"关岛":           "GU",
		"几内亚比绍":        "GW",
		"圭亚那":          "GY",
		"香港":           "HK",
		"赫德岛和麦克唐纳群岛": "HM",
		"洪都拉斯":       "HN",
		"克罗地亚":       "HR",
		"海地":         "HT",
		"匈牙利":        "HU",
		"印度尼西亚":      "ID",
		"爱尔兰":        "IE",
		"以色列":        "IL",
		"马恩岛":        "IM",
		"印度":         "IN",
		"英属印度洋领地":    "IO",
		"伊拉克":        "IQ",
		"伊朗":         "IR",
		"冰岛":         "IS",
		"意大利":        "IT",
		"泽西岛":        "JE",
		"牙买加":        "JM",
		"约旦":         "JO",
		"日本":         "JP",
		"肯尼亚":        "KE",
		"吉尔吉斯斯坦":     "KG",
		"柬埔寨":        "KH",
		"基里巴斯":       "KI",
		"科摩罗":        "KM",
		"圣基茨和尼维斯":    "KN",
		"朝鲜":         "KP",
		"韩国":         "KR",
		"科威特":        "KW",
		"开曼群岛":       "KY",
		"哈萨克斯坦":      "KZ",
		"老挝":         "LA",
		"黎巴嫩":        "LB",
		"圣卢西亚":       "LC",
		"列支敦士登":      "LI",
		"斯里兰卡":       "LK",
		"利比里亚":       "LR",
		"莱索托":        "LS",
		"立陶宛":        "LT",
		"卢森堡":        "LU",
		"拉脱维亚":       "LV",
		"利比亚":        "LY",
		"摩洛哥":        "MA",
		"摩纳哥":        "MC",
		"摩尔多瓦":       "MD",
		"黑山":         "ME",
		"法属圣马丁":      "MF",
		"马达加斯加":      "MG",
		"马绍尔群岛":      "MH",
		"马其顿":        "MK",
		"马里":         "ML",
		"缅甸":         "MM",
		"蒙古":         "MN",
		"澳门":         "MO",
		"北马里亚纳群岛":    "MP",
		"马提尼克岛":      "MQ",
		"毛里塔尼亚":      "MR",
		"蒙特塞拉特岛":     "MS",
		"马耳他":        "MT",
		"毛里求斯":       "MU",
		"马尔代夫":       "MV",
		"马拉维":        "MW",
		"墨西哥":        "MX",
		"马来西亚":       "MY",
		"莫桑比克":       "MZ",
		"纳米比亚":       "NA",
		"新喀里多尼亚":     "NC",
		"尼日尔":        "NE",
		"诺福克岛":       "NF",
		"尼日利亚":       "NG",
		"尼加拉瓜":       "NI",
		"纳戈尔诺-卡拉巴赫":  "NK",
		"荷兰":         "NL",
		"挪威":         "NO",
		"尼泊尔":        "NP",
		"瑙鲁":         "NR",
		"纽埃岛":        "NU",
		"新西兰":        "NZ",
		"阿曼":         "OM",
		"巴拿马":        "PA",
		"秘鲁":         "PE",
		"法属波利尼西亚":    "PF",
		"巴布亚新几内亚":    "PG",
		"菲律宾":        "PH",
		"巴基斯坦":       "PK",
		"波兰":         "PL",
		"圣皮埃尔和密克隆群岛":  "PM",
		"皮特凯恩群岛":      "PN",
		"波多黎各":        "PR",
		"巴勒斯坦":        "PS",
		"葡萄牙":         "PT",
		"帕劳":          "PW",
		"巴拉圭":         "PY",
		"卡塔尔":         "QA",
		"留尼汪岛":        "RE",
		"罗马尼亚":        "RO",
		"塞尔维亚":        "RS",
		"俄罗斯":         "RU",
		"卢旺达":         "RW",
		"沙特阿拉伯":       "SA",
		"所罗门群岛":       "SB",
		"塞舌尔":         "SC",
		"苏丹":          "SD",
		"瑞典":          "SE",
		"新加坡":         "SG",
		"圣赫勒拿":        "SH",
		"斯洛文尼亚":       "SI",
		"斯瓦尔巴群岛和扬马延岛": "SJ",
		"斯洛伐克":        "SK",
		"塞拉利昂":        "SL",
		"圣马力诺":        "SM",
		"塞内加尔":        "SN",
		"索马里":         "SO",
		"苏里南":         "SR",
		"南苏丹":         "SS",
		"圣多美和普林西比":    "ST",
		"萨尔瓦多":        "SV",
		"荷属圣马丁":       "SX",
		"叙利亚":         "SY",
		"斯威士兰":        "SZ",
		"特克斯和凯科斯群岛":   "TC",
		"乍得":          "TD",
		"法属南部领地":      "TF",
		"多哥":          "TG",
		"泰国":          "TH",
		"塔吉克斯坦":       "TJ",
		"托克劳群岛":       "TK",
		"东帝汶":         "TL",
		"土库曼斯坦":       "TM",
		"突尼斯":         "TN",
		"汤加":          "TO",
		"土耳其":         "TR",
		"特立尼达和多巴哥":    "TT",
		"图瓦卢":         "TV",
		"台湾":          "TW",
		"坦桑尼亚":        "TZ",
		"乌克兰":         "UA",
		"乌干达":         "UG",
		"美国本土外小岛屿":    "UM",
		"美国":          "US",
		"乌拉圭":         "UY",
		"乌兹别克斯坦":      "UZ",
		"梵蒂冈":         "VA",
		"圣文森特和格林纳丁斯":  "VC",
		"委内瑞拉":        "VE",
		"英属维尔京群岛":     "VG",
		"美属维尔京群岛":     "VI",
		"越南":          "VN",
		"瓦努阿图":        "VU",
		"瓦利斯和富图纳群岛":   "WF",
		"萨摩亚":         "WS",
		"也门":          "YE",
		"马约特":         "YT",
		"南非":          "ZA",
		"赞比亚":         "ZM",
		"津巴布韦":        "ZW",
	}

	irregularCountries = map[string]bool{
		"012.NET 骨干网":                  true,
		"0LOSS.COM":                    true,
		"114DNS.COM":                   true,
		"1AND1.COM":                    true,
		"1AND1.COM 骨干网":                true,
		"3M.COM":                       true,
		"3QSDN.COM":                    true,
		"51EIDC.COM":                   true,
		"6CONNECT.COM":                 true,
		"A2WEBHOSTING.COM":             true,
		"AAGICO.COM":                   true,
		"AARNET.EDU.AU 骨干网":            true,
		"ABSATELLITE.COM 骨干网":          true,
		"ACEDC 骨干网":                    true,
		"AC.ME":                        true,
		"ADOBE.COM":                    true,
		"ADVANCEDHOSTERS.COM":          true,
		"AEDNS.AE":                     true,
		"AEROTEK.COM.TR":               true,
		"AETHOSTING.COM":               true,
		"AFILIAS.INFO":                 true,
		"AGARTO.COM":                   true,
		"A.GTLD.BIZ":                   true,
		"AIRTEL.COM 骨干网":               true,
		"AKAMAI.COM":                   true,
		"ALCOM.AX 骨干网":                 true,
		"ALENTUS":                      true,
		"ALIBABA.COM 骨干网":              true,
		"ALIDNS.COM":                   true,
		"ALIYUN.COM":                   true,
		"ALIYUN":                       true,
		"ALTER.NET 骨干网":                true,
		"AMAZON.COM":                   true,
		"AMAZON.COM 骨干网":               true,
		"AMCBB 骨干网":                    true,
		"AMNIC.NET":                    true,
		"ANEXIA-IT.COM":                true,
		"ANYCAST.IO":                   true,
		"AORTA 骨干网":                    true,
		"APNIC.NET":                    true,
		"APPLE.COM":                    true,
		"APPLE.COM 骨干网":                true,
		"APPNEXUS.COM":                 true,
		"APPRIVER.COM":                 true,
		"ARKADIN.COM":                  true,
		"A-ROOT-SERVERS":               true,
		"ARTFILES.COM":                 true,
		"ARVAN.CLOUD":                  true,
		"ARYAKA.COM":                   true,
		"ASC.EDU 骨干网":                  true,
		"ASK.COM":                      true,
		"ASTUTEINTERNET.COM":           true,
		"ASTUTEINTERNET.COM 骨干网":       true,
		"ATECHMEDIA":                   true,
		"ATHEA.AR":                     true,
		"ATLANTECH.NET 骨干网":            true,
		"ATRATO.COM 骨干网":               true,
		"ATT.COM":                      true,
		"ATT.COM 骨干网":                  true,
		"AUDA.ORG.AU":                  true,
		"AUSREGISTRY.COM.AU":           true,
		"AUTOMATTIC":                   true,
		"AVANTIPLC.COM 骨干网":            true,
		"AVAST.COM":                    true,
		"AZION.COM.BR":                 true,
		"Azure-DNS":                    true,
		"BACKBONE.IS 骨干网":              true,
		"BAHNHOF.NET 骨干网":              true,
		"BAIDU.COM":                    true,
		"BAREFRUIT.CO.UK":              true,
		"BELGACOM 骨干网":                 true,
		"BELL.CA 骨干网":                  true,
		"BELLCA 骨干网":                   true,
		"BETAIDC.COM":                  true,
		"BGP.NET 骨干网":                  true,
		"B.GTLD.BIZ":                   true,
		"BITGRAVITY.COM":               true,
		"BLACKBERRY.COM":               true,
		"BLIX.COM":                     true,
		"BLIZZARD.COM 骨干网":             true,
		"BOOKING.COM":                  true,
		"B-ROOT-SERVERS":               true,
		"BSONETWORK.COM 骨干网":           true,
		"BT.COM 骨干网":                   true,
		"BUNNYCDN.COM":                 true,
		"BUYVM.NET":                    true,
		"C4L.CO.UK 骨干网":                true,
		"CACHEFLY.COM":                 true,
		"CARRIER2CARRIER 骨干网":          true,
		"CA-SERVERS.CA":                true,
		"CDLAN.IT 骨干网":                 true,
		"CDN77.COM":                    true,
		"CDNETWORKS.COM":               true,
		"CEDEXIS.COM":                  true,
		"CENTRALNIC.COM":               true,
		"CERT.AT":                      true,
		"C.GTLD.BIZ":                   true,
		"CHELLO 骨干网":                   true,
		"CHINANETCENTER.COM":           true,
		"CHOOPADNS.COM":                true,
		"CHTGLOBAL.COM 骨干网":            true,
		"CIRA.CA":                      true,
		"CITI.COM":                     true,
		"CITRIX.COM 骨干网":               true,
		"CITYTELECOM.RU 骨干网":           true,
		"CLARKSYS.COM":                 true,
		"CLEARHOST.CO.UK":              true,
		"CLOUDACCESS.NET":              true,
		"CLOUDBROKERS.AT":              true,
		"CLOUDDNS.NET":                 true,
		"CLOUDFLARE.COM":               true,
		"CLOUDFLOORDNS.COM":            true,
		"CLOUD.GOOGLE.COM":             true,
		"CLOUVIDER.NET":                true,
		"CMC.IQ":                       true,
		"CNET.NET":                     true,
		"CNNIC.CN":                     true,
		"COGECOPEER1.COM":              true,
		"COGENTCO.COM":                 true,
		"COGENTCO.COM 骨干网":             true,
		"COLT.NET 骨干网":                 true,
		"COLUMBUS-NETWORKS 骨干网":        true,
		"COMNET 骨干网":                   true,
		"COMODO.COM":                   true,
		"CONEXIMGLOBAL.NET":            true,
		"CONPLEX.IO":                   true,
		"CONSOLECONNECT.COM 骨干网":       true,
		"CONTINENT8.COM 骨干网":           true,
		"CORE-BACKBONE.COM 骨干网":        true,
		"COREINTERNET.CO.UK":           true,
		"CORELINK.IO":                  true,
		"CPRM.NET 骨干网":                 true,
		"CRASHLYTICS.COM":              true,
		"C-ROOT-SERVERS":               true,
		"CVNT.NET":                     true,
		"CWASIA.NET 骨干网":               true,
		"CYANLINK.NET":                 true,
		"CYBERA.NET":                   true,
		"DAILYMOTION.COM":              true,
		"DAL.NET":                      true,
		"DATAHOP 骨干网":                  true,
		"DATAPATH.IO":                  true,
		"DATAPIPE.COM 骨干网":             true,
		"DATPIXEL.NET":                 true,
		"DDITSERVICES 骨干网":             true,
		"DENIC.DE":                     true,
		"DEVCAPSULE.COM":               true,
		"DEVELOPMENTENTITY.WORK":       true,
		"DIALPAD.COM 骨干网":              true,
		"DIGIDESERT.NET":               true,
		"DIGITAL.HT":                   true,
		"DIGIWEB.IE 骨干网":               true,
		"DIPEX.RU":                     true,
		"DISNEY.COM":                   true,
		"DISTILNETWORKS.COM":           true,
		"DNS.AR":                       true,
		"DNS.BE":                       true,
		"DNSBIRD.NET":                  true,
		"DNS.BR":                       true,
		"DNSFILTER.COM":                true,
		"DNSIMPLE.COM":                 true,
		"DNS.LU":                       true,
		"DNSNOVA.COM":                  true,
		"DNS-OARC.NET":                 true,
		"DNSPOD.COM":                   true,
		"DNSREC.MEO.WS":                true,
		"DOMENESHOP.NO":                true,
		"DOSARREST.COM":                true,
		"DOTQUAD.COM":                  true,
		"DOTQUAD.COM 骨干网":              true,
		"DQECOM.COM 骨干网":               true,
		"DREAMSCAPENETWORKS.COM":       true,
		"D-ROOT-SERVERS":               true,
		"DROPBOX.COM 骨干网":              true,
		"DROPBOX 骨干网":                  true,
		"DUDICOM.DK":                   true,
		"DUODECADITS.COM":              true,
		"DYN.COM":                      true,
		"E24DNS.COM":                   true,
		"EASYDNS.COM":                  true,
		"EASYNET.NET 骨干网":              true,
		"EBAY.COM 骨干网":                 true,
		"ECOMLTD 骨干网":                  true,
		"EDGECAST.COM":                 true,
		"EDPNET.NET 骨干网":               true,
		"EDSI-TECH.COM":                true,
		"EGIHOSTING":                   true,
		"E.GTLD.BIZ":                   true,
		"ELAUWIT.COM":                  true,
		"ELISA.FI 骨干网":                 true,
		"ELLIEMAE.COM 骨干网":             true,
		"EQUINIX.COM 骨干网":              true,
		"ERICSSONUDN.COM":              true,
		"E-ROOT-SERVERS":               true,
		"ESNET 骨干网":                    true,
		"ESOSOFT.NET":                  true,
		"euNetworks 骨干网":               true,
		"EXA.NET.UK 骨干网":               true,
		"FACEBOOK.COM":                 true,
		"FACEBOOK.COM 骨干网":             true,
		"FALCO-NETWORKS.COM":           true,
		"FARSNEWS.COM":                 true,
		"FASTLY.COM":                   true,
		"FFASTFILL.COM":                true,
		"F.GTLD.BIZ":                   true,
		"FIBERAX.COM 骨干网":              true,
		"FIBERDROP.NET":                true,
		"FIBER.GOOGLE.COM 骨干网":         true,
		"fibernetdirect.com 骨干网":       true,
		"FIBTEL.NET":                   true,
		"FIDO.NET":                     true,
		"FIORD.RU 骨干网":                 true,
		"FLOPS.RU":                     true,
		"FLYCAT.IO 骨干网":                true,
		"FONDATIONRESTENA":             true,
		"FORCEPOINT.COM":               true,
		"FORTINET.COM":                 true,
		"FREENOM.COM":                  true,
		"F-ROOT-SERVERS":               true,
		"GADITEK.COM":                  true,
		"GANDI.NET":                    true,
		"GANDI.NET 骨干网":                true,
		"GCORE.LU":                     true,
		"GDNS.SO":                      true,
		"GEANT 骨干网":                    true,
		"GEOSCALING.COM":               true,
		"GHX.COM":                      true,
		"GIGAS.COM":                    true,
		"GILATSATCOM 骨干网":              true,
		"GINERNET.COM":                 true,
		"GlobalCloudXchange 骨干网":       true,
		"GLOBALCOM 骨干网":                true,
		"GLOBALCONNECT.NET 骨干网":        true,
		"GLOBALTRANSIT.NET 骨干网":        true,
		"GLOBENET.NET 骨干网":             true,
		"GODADDY.COM":                  true,
		"GODADDY.COM 骨干网":              true,
		"GOOGLE.COM":                   true,
		"GOOGLE.COM 骨干网":               true,
		"GOOGLEVPN":                    true,
		"GOSCOMB 骨干网":                  true,
		"GRADWELL.COM":                 true,
		"GRANSY.COM":                   true,
		"GRATISDNS.DK":                 true,
		"G-ROOT-SERVERS":               true,
		"GTT.NET 骨干网":                  true,
		"HAWKHOST.COM":                 true,
		"HEG.COM 骨干网":                  true,
		"HE.NET":                       true,
		"HE.NET 骨干网":                   true,
		"HERE.COM 骨干网":                 true,
		"HGC.COM.HK 骨干网":               true,
		"HIBERNIACDN.COM":              true,
		"HIGHWINDS.COM":                true,
		"HIGHWINDS.COM 骨干网":            true,
		"HILLSIDENEWMEDIA.COM":         true,
		"HOPONE.NET 骨干网":               true,
		"HOST1PLUS.COM":                true,
		"HOSTEMO 骨干网":                  true,
		"HOSTING4REAL.NET":             true,
		"HOSTISERVER.COM":              true,
		"HOST.NET 骨干网":                 true,
		"HOSTNOC 骨干网":                  true,
		"HOSTUS.US":                    true,
		"HOSTVIRTUAL.COM":              true,
		"HOSTWAY.COM":                  true,
		"HOTWIRECOMMUNICATION.COM 骨干网": true,
		"HP 骨干网":                       true,
		"I3D.NET":                      true,
		"IANA-SERVERS.NET":             true,
		"ICANN.ORG":                    true,
		"ICS.FORTH.GR":                 true,
		"IFXNETWORKS.COM 骨干网":          true,
		"IGLOO.TO":                     true,
		"IGNUM.CZ":                     true,
		"IIJ.AD.JP":                    true,
		"IINET.NET.AU 骨干网":             true,
		"IMPLETEC.COM":                 true,
		"INCAPSULA.COM":                true,
		"INIT7.NET 骨干网":                true,
		"INNOVA":                       true,
		"INSTARTLOGIC.COM":             true,
		"INSTART":                      true,
		"INTELSATONE 骨干网":              true,
		"INTERNAP.COM":                 true,
		"INTERNET2 骨干网":                true,
		"INTERNETNAMESFORBUSINESS.COM": true,
		"INTEROUTE.COM 骨干网":            true,
		"INTERROUTE 骨干网":               true,
		"INVITEL.NET":                  true,
		"IPIP.NET":                     true,
		"IP-MAX 骨干网":                   true,
		"IP-ONLY.SE 骨干网":               true,
		"IPTP 骨干网":                     true,
		"IPTRANSIT 骨干网":                true,
		"I-ROOT-SERVERS":               true,
		"ISC.ORG":                      true,
		"ISC 骨干网":                      true,
		"ISPRIME.COM":                  true,
		"J-ROOT-SERVERS":               true,
		"KAIAGLOBAL 骨干网":               true,
		"KAMATERA.COM":                 true,
		"KARTINAWORLD.COM":             true,
		"KDDI.COM 骨干网":                 true,
		"K.GTLD.BIZ":                   true,
		"KLAYER.COM":                   true,
		"KNET.CN":                      true,
		"KNIPP.DE":                     true,
		"KOBALT.DK":                    true,
		"KOBO.COM 骨干网":                 true,
		"KPN.COM 骨干网":                  true,
		"K-ROOT-SERVERS":               true,
		"KT.COM 骨干网":                   true,
		"LAYER42 骨干网":                  true,
		"LAZADA.COM":                   true,
		"LEASEWEBCDN.COM":              true,
		"LEASEWEB 骨干网":                 true,
		"LEVEL3.COM":                   true,
		"LEVEL3.COM 骨干网":               true,
		"LG DACOM 骨干网":                 true,
		"LIFELINK.RU":                  true,
		"LIGHTEDGE.COM 骨干网":            true,
		"LIGHTOWER.COM 骨干网":            true,
		"LIMELIGHT.COM":                true,
		"LIMELIGHT.COM 骨干网":            true,
		"LINK11.DE 骨干网":                true,
		"LINKEDIN 骨干网":                 true,
		"LINKEY.RU 骨干网":                true,
		"LINKWORK.DK":                  true,
		"LINODE.COM":                   true,
		"LINXTELECOM 骨干网":              true,
		"LIQUIDTELECOM.COM 骨干网":        true,
		"LITTLEMOE.NET":                true,
		"LIVEAIR.NET 骨干网":              true,
		"LOGIC.BM 骨干网":                 true,
		"L-ROOT-SERVERS":               true,
		"LUADNS.COM":                   true,
		"M247.COM":                     true,
		"M247.COM 骨干网":                 true,
		"MAINLOOP.SE":                  true,
		"MANAGEDWAY.COM":               true,
		"MASERGY.COM":                  true,
		"MASERGY 骨干网":                  true,
		"MASTERBASE.COM":               true,
		"MAVIDENIZ.COM.TR":             true,
		"MAXCDN.COM":                   true,
		"MAYERBROWN.COM":               true,
		"MCPROHOSTING.COM":             true,
		"M-D.NET":                      true,
		"MEDIANETWORKSERVICES.COM":     true,
		"MEDIANETWORKSERVICES.COM 骨干网": true,
		"MELBICOM.NET":                 true,
		"MERAKI.COM":                   true,
		"MESH.EU 骨干网":                  true,
		"MICHAEL-KEHOE":                true,
		"MICROSOFT.COM":                true,
		"MICROSOFT 骨干网":                true,
		"MIMECAST.COM":                 true,
		"MIRROR-IMAGE.COM":             true,
		"MISAKA.IO":                    true,
		"MISAKA.IO 骨干网":                true,
		"MOJOHOST.COM":                 true,
		"MONOSOLUTIONS.COM":            true,
		"M-ROOT-SERVERS":               true,
		"MTC 骨干网":                      true,
		"MTN 骨干网":                      true,
		"MTS.RU 骨干网":                   true,
		"MYNIC.MY":                     true,
		"NEOCITIES.ORG":                true,
		"NEOLOGY.CO.ZA":                true,
		"Neotelecoms 骨干网":              true,
		"NETAPPLICATIONS.COM":          true,
		"NETASSIST.UA 骨干网":             true,
		"NETFLIX.COM":                  true,
		"NETNAMES.COM":                 true,
		"NETNOD.SE":                    true,
		"NETREGISTRY.COM.AU":           true,
		"NETRIPLEX.COM":                true,
		"NEWWORLDTEL 骨干网":              true,
		"NEXCESS.NET":                  true,
		"NEXTHOP.NO":                   true,
		"NEXUSGUARD.COM":               true,
		"NEXUSGUARD.COM 骨干网":           true,
		"NIC.AT":                       true,
		"NIC.CH":                       true,
		"NIC.CL":                       true,
		"NIC.CZ":                       true,
		"NIC.DK":                       true,
		"NIC.FR":                       true,
		"NIC.MX":                       true,
		"NIKE.COM":                     true,
		"NJAL.LA":                      true,
		"NORDU.NET 骨干网":                true,
		"NPIX.NET.NP":                  true,
		"NS1.COM":                      true,
		"NSOF.IO":                      true,
		"NTT.COM":                      true,
		"NTT.COM 骨干网":                  true,
		"NUBELA.CO":                    true,
		"NUMERICABLE.FR 骨干网":           true,
		"O3B-NETWORKS.COM":             true,
		"OMNIS.COM":                    true,
		"ONAPP.COM":                    true,
		"OPENBSD.ORG.IL":               true,
		"OPENDNS.COM":                  true,
		"OPTICFUSION.NET 骨干网":          true,
		"ORACLE.COM 骨干网":               true,
		"ORANGE.COM 骨干网":               true,
		"OVH.COM":                      true,
		"OVH.COM 骨干网":                  true,
		"PACKET.NET":                   true,
		"PACNET.COM":                   true,
		"PACNET.COM 骨干网":               true,
		"PAGESAT":                      true,
		"PCCW 骨干网":                     true,
		"PCH.NET":                      true,
		"PCH.NET 骨干网":                  true,
		"PEAK10.COM":                   true,
		"PEARSON.COM":                  true,
		"PEER1 骨干网":                    true,
		"PHOTONVPS.COM":                true,
		"PLANETHOSTER.NET":             true,
		"PLANISYS.COM":                 true,
		"PORTLANE 骨干网":                 true,
		"PRAGER-IT.COM":                true,
		"PRETECS.COM":                  true,
		"PRIMUSTEL.CA 骨干网":             true,
		"PRODUBAN.COM":                 true,
		"PROFIHOST.COM":                true,
		"PROLEXIC.COM":                 true,
		"PROLEXIC.COM 骨干网":             true,
		"PROLEXIC 骨干网":                 true,
		"PSYCHZ.NET":                   true,
		"PUBLICDOMAINREGISTRY.COM":     true,
		"PULSEPOINT.COM":               true,
		"QRATOR.NET":                   true,
		"QSC.DE 骨干网":                   true,
		"QUAD9.NET":                    true,
		"QUADRANET.COM":                true,
		"QUANTCAST.COM":                true,
		"QWEST.NET 骨干网":                true,
		"QWEST.NET骨干网":                 true,
		"RAGE4.COM":                    true,
		"RASCOM.RU 骨干网":                true,
		"RCN 骨干网":                      true,
		"REDCLARA 骨干网":                 true,
		"REFLECTED.NET":                true,
		"RIM 骨干网":                      true,
		"RINGCENTRAL.COM":              true,
		"RINGCENTRAL.COM 骨干网":          true,
		"RIOTGAMES 骨干网":                true,
		"RIPE.NET":                     true,
		"RIU.EDU.AR":                   true,
		"ROBTEX.COM":                   true,
		"ROLLERNET.US":                 true,
		"RT.RU 骨干网":                    true,
		"SAFEDNS.COM":                  true,
		"SAFEVALUE.PRO":                true,
		"SAGLAYICI.COM":                true,
		"SALESFORCE 骨干网":               true,
		"SAMIR.CA":                     true,
		"SAVVIS.NET 骨干网":               true,
		"SCIP.ES":                      true,
		"SDNS.CN":                      true,
		"SEACOM.MU 骨干网":                true,
		"SECTION.IO":                   true,
		"SECUREDSERVERS.COM":           true,
		"SEEWEB":                       true,
		"SELECTEL.RU":                  true,
		"SERV-AC.COM":                  true,
		"SERVERS.COM":                  true,
		"SFERA.NET":                    true,
		"SG.GS":                        true,
		"SG.GS 骨干网":                    true,
		"SHOPIFY.COM":                  true,
		"SIEL.SI":                      true,
		"SIFY.COM 骨干网":                 true,
		"SINGTEL.COM 骨干网":              true,
		"SITA.AERO 骨干网":                true,
		"SKHOSTING.EU":                 true,
		"SKYEBYNOMINUM.COM":            true,
		"SKYPARKCDN.RU":                true,
		"SKYVISION.NET 骨干网":            true,
		"SMC.LI":                       true,
		"SMULE.COM":                    true,
		"SOFTLAYER.COM":                true,
		"SOFTLAYER.COM 骨干网":            true,
		"SPACEDUMP.NET":                true,
		"SpectrumNet 骨干网":              true,
		"SPECTRUMNET 骨干网":              true,
		"SPIRITCOM.COM 骨干网":            true,
		"SPRINT.COM":                   true,
		"SQUIZ.NET":                    true,
		"STACKPATH.COM":                true,
		"STAMINUS.NET":                 true,
		"STAMINUS.NET 骨干网":             true,
		"STARRYDNS.COM":                true,
		"STREAMING.CO.NZ":              true,
		"SUCURI.NET":                   true,
		"SUNGARDRS.COM 骨干网":            true,
		"SUNRISE 骨干网":                  true,
		"SUPREMEBYTES.COM":             true,
		"SUPREMEBYTES.COM 骨干网":         true,
		"SURF.NL":                      true,
		"SYMANTEC.COM":                 true,
		"SYNAPSEGLOBAL.COM":            true,
		"SYNOPSYS.COM":                 true,
		"TAGHOS.COM.BR":                true,
		"TALAMUS.COM":                  true,
		"TATACOMMUNICATIONS.COM 骨干网":   true,
		"TDC.DK 骨干网":                   true,
		"TELE2.COM 骨干网":                true,
		"TELECOMITALIA.SM":             true,
		"TELECOM.KZ":                   true,
		"TELECOM.KZ 骨干网":               true,
		"TELEFONICA.COM 骨干网":           true,
		"TELEKOM.DE 骨干网":               true,
		"TELENOR.COM 骨干网":              true,
		"TELENOR 骨干网":                  true,
		"TELETOK.TK":                   true,
		"TELIA.COM 骨干网":                true,
		"TELIN 骨干网":                    true,
		"TELKOM.CO.ZA 骨干网":             true,
		"TELSTRA.COM 骨干网":              true,
		"TENCENT.COM":                  true,
		"TERAGO 骨干网":                   true,
		"TERRA.COM.BR":                 true,
		"TERREMARK.COM 骨干网":            true,
		"THREATSTOP.COM":               true,
		"TIBUS 骨干网":                    true,
		"TIERPOINT.COM":                true,
		"TIGGEE.COM":                   true,
		"TISPARKLE.COM 骨干网":            true,
		"TMNET 骨干网":                    true,
		"T-MOBILE.CZ 骨干网":              true,
		"TMXATRIUM.COM 骨干网":            true,
		"TOPNET.UA 骨干网":                true,
		"TOTALUPTIME.COM":              true,
		"TRANSTELCO.NET 骨干网":           true,
		"TRANSTELECOM 骨干网":             true,
		"TRENDMICRO.COM":               true,
		"TTK.RU 骨干网":                   true,
		"TURKTELEKOM.COM.TR 骨干网":       true,
		"TWCC.COM 骨干网":                 true,
		"TWGATE.NET 骨干网":               true,
		"TWITCH.TV":                    true,
		"TWITTER":                      true,
		"TWITTER 骨干网":                  true,
		"TYPCN.COM 骨干网":                true,
		"UCDN.COM":                     true,
		"UGO.COMPANY":                  true,
		"ULTRADNS.COM":                 true,
		"UNDERNET.ORG":                 true,
		"UNIVIE.AC.AT":                 true,
		"USSIGNAL.COM 骨干网":             true,
		"UUNET 骨干网":                    true,
		"UWORLD.SE":                    true,
		"VALVESOFTWARE":                true,
		"VELDER.LI":                    true,
		"VELLANCE.COM":                 true,
		"VERISIGN.COM":                 true,
		"VERISIGN.COM 骨干网":             true,
		"VERIZON.COM":                  true,
		"VERIZON.COM 骨干网":              true,
		"VIAWEST.COM":                  true,
		"VIAWEST.COM 骨干网":              true,
		"VIDILLION.COM":                true,
		"VIKINGHOST.COM":               true,
		"VIRTELA 骨干网":                  true,
		"VIRTUASERVER.COM.BR":          true,
		"VIRTUTEL.COM.AU":              true,
		"VIRTUTEL.COM.AU 骨干网":          true,
		"VITALWERKS.COM":               true,
		"VOCUS.COM.AU 骨干网":             true,
		"VODAFONE.COM 骨干网":             true,
		"VOXEL.NET":                    true,
		"VOXEL.NET 骨干网":                true,
		"VOXILITY.COM":                 true,
		"VOXILITY.COM 骨干网":             true,
		"VPSQUAN.COM":                  true,
		"VULTR.COM":                    true,
		"WANWIRE.COM":                  true,
		"WEB2OBJECTS.COM":              true,
		"WEBAIR.COM":                   true,
		"WEBEX.COM 骨干网":                true,
		"WINKSTREAMING.COM":            true,
		"WIPRO.COM":                    true,
		"WIPRO 骨干网":                    true,
		"WOLFE 骨干网":                    true,
		"WORLDNS.NET":                  true,
		"X4B.NET":                      true,
		"XCONNECT24 骨干网":               true,
		"XTCN.COM":                     true,
		"XTOM.COM":                     true,
		"YAHOO.COM":                    true,
		"YAHOO.COM 骨干网":                true,
		"YOUTUBE.COM":                  true,
		"YUN-IDC.COM":                  true,
		"YUN-IDC.COM 骨干网":              true,
		"ZAYO.COM 骨干网":                 true,
		"ZILORE":                       true,
		"ZORINS.CO.UK":                 true,
		"ZSCALER.COM":                  true,
		"ZVONKOVA":                     true,
		"ZXITY.UK":                     true,
		"亚太地区":                         true,
		"保留地址":                         true,
		"共享地址":                         true,
		"北美地区":                         true,
		"局域网":                          true,
		"拉美地区":                         true,
		"本地链路":                         true,
		"本机地址":                         true,
		"欧盟":                           true,
		"科索沃":                          true, // XK
		"非洲地区":                         true,
	}
)

func getCountryCode(c string) string {
	if v, ok := countryCodes[c]; ok {
		return v
	}
	return ""
}
